default l0
menu title EMB3531 Headless Server
prompt 1
timeout 1

label l0
 menu label Linux 6.18.24
 linux /Image
 fdt /dtb/rk3399-emb3531.dtb
 append root=/dev/mmcblk2p4 rootwait rw console=ttyS2,115200 net.ifnames=0 earlycon=uart8250,mmio32,0xff1a0000
